### PR TITLE
 Added plugins for google map setings

### PR DESCRIPTION
**Pull request by Mayenin**

### CODE REVIEW

**Comment by Mayenin** [comment]
HeeY  GUYS. See dat ):  .

**Comment by Willticha** [comment]
All good to go

**Comment by waleadekunle** [comment]
Here we go. Lets ride on together

**Comment by ferdmil237** [comment]
good

**Comment by Willticha** [comment]
Good

**Comment by Azar-cpu** [comment]
GREAT WORK

**Comment by waleadekunle** [comment]
Cool

**Pull request merged**
